# Generated by Django 4.2.2 on 2023-06-30 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=90)),
                ('category_slogan', models.CharField(max_length=40)),
                ('category_img', models.ImageField(upload_to='assets')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=40)),
                ('subcategory_img', models.ImageField(upload_to='assets')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku', models.CharField(max_length=30)),
                ('product_name', models.CharField(max_length=150)),
                ('product_shortdesc', models.CharField(max_length=250)),
                ('product_longdesc', models.TextField()),
                ('product_mrp', models.FloatField(default=1.0)),
                ('product_taxrate', models.PositiveIntegerField(default=18)),
                ('product_weight', models.PositiveBigIntegerField(default=500)),
                ('product_piece', models.PositiveIntegerField(default=1)),
                ('product_stock', models.PositiveIntegerField(default=0)),
                ('product_isactive', models.BooleanField(default=False)),
                ('product_img1', models.ImageField(blank=True, null=True, upload_to='product')),
                ('product_img2', models.ImageField(blank=True, null=True, upload_to='product')),
                ('product_img3', models.ImageField(blank=True, null=True, upload_to='product')),
                ('product_img4', models.ImageField(blank=True, null=True, upload_to='product')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.category')),
                ('product_subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.subcategory')),
            ],
        ),
    ]
